# -*- coding: utf-8 -*-
"""Room_allotment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UB9_elPKRRt0u4cgRIj_uNyjbx0_3Nvf
"""

rooms = {
    101: None, 102: None, 103: None, 104: None, 105: None,
    106: None, 107: None, 108: None, 109: None, 110: None
}

occupied = set()

n = int(input("Enter the number of students: "))

for i in range(n):
    name = input("Enter the name of the student: ")
    allotted = False

    for room_no, student in rooms.items():
        if student is None:
            rooms[room_no] = name
            occupied.add(room_no)
            print(f"{name} has been allotted room number {room_no}")
            allotted = True
            break

    if not allotted:
        print("Sorry, all the rooms are occupied.")
        break

print("\nFinal Room Allotment:")
for room_no, student in rooms.items():
    print(room_no, "-", student)

print("\nOccupied Rooms:", occupied)